package Modelos;
// Generated 29/11/2017 08:00:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private Integer idMaterial;
     private String nombre;
     private double cantidad;
     private String unidadMedida;
     private Set<Ingreso> ingresos = new HashSet<Ingreso>(0);
     private Set<TipoProductoYMaterial> tipoProductoYMaterials = new HashSet<TipoProductoYMaterial>(0);
     private Set<Salida> salidas = new HashSet<Salida>(0);

    public Material() {
    }

	
    public Material(String nombre, double cantidad, String unidadMedida) {
        this.nombre = nombre;
        this.cantidad = cantidad;
        this.unidadMedida = unidadMedida;
    }
    public Material(String nombre, double cantidad, String unidadMedida, Set<Ingreso> ingresos, Set<TipoProductoYMaterial> tipoProductoYMaterials, Set<Salida> salidas) {
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.unidadMedida = unidadMedida;
       this.ingresos = ingresos;
       this.tipoProductoYMaterials = tipoProductoYMaterials;
       this.salidas = salidas;
    }
   
    public Integer getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(Integer idMaterial) {
        this.idMaterial = idMaterial;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public String getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public Set<Ingreso> getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set<Ingreso> ingresos) {
        this.ingresos = ingresos;
    }
    public Set<TipoProductoYMaterial> getTipoProductoYMaterials() {
        return this.tipoProductoYMaterials;
    }
    
    public void setTipoProductoYMaterials(Set<TipoProductoYMaterial> tipoProductoYMaterials) {
        this.tipoProductoYMaterials = tipoProductoYMaterials;
    }
    public Set<Salida> getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set<Salida> salidas) {
        this.salidas = salidas;
    }




}


