package Modelos;
// Generated 29/11/2017 08:00:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer idPedido;
     private Usuario usuario;
     private String estado;
     private String clientes;
     private Date fecha;
     private Set<Salida> salidas = new HashSet<Salida>(0);
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Pedido() {
    }

	
    public Pedido(Usuario usuario, String estado, String clientes, Date fecha) {
        this.usuario = usuario;
        this.estado = estado;
        this.clientes = clientes;
        this.fecha = fecha;
    }
    public Pedido(Usuario usuario, String estado, String clientes, Date fecha, Set<Salida> salidas, Set<Producto> productos) {
       this.usuario = usuario;
       this.estado = estado;
       this.clientes = clientes;
       this.fecha = fecha;
       this.salidas = salidas;
       this.productos = productos;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getClientes() {
        return this.clientes;
    }
    
    public void setClientes(String clientes) {
        this.clientes = clientes;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<Salida> getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set<Salida> salidas) {
        this.salidas = salidas;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


