package Modelos;
// Generated 29/11/2017 08:00:02 PM by Hibernate Tools 4.3.1



/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Pedido pedido;
     private TipoProducto tipoProducto;
     private double cantidad;
     private String estado;
     private boolean clienteMaterial;
     private String descripcion;

    public Producto() {
    }

    public Producto(Pedido pedido, TipoProducto tipoProducto, double cantidad, String estado, boolean clienteMaterial, String descripcion) {
       this.pedido = pedido;
       this.tipoProducto = tipoProducto;
       this.cantidad = cantidad;
       this.estado = estado;
       this.clienteMaterial = clienteMaterial;
       this.descripcion = descripcion;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public TipoProducto getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(TipoProducto tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public boolean isClienteMaterial() {
        return this.clienteMaterial;
    }
    
    public void setClienteMaterial(boolean clienteMaterial) {
        this.clienteMaterial = clienteMaterial;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


