package Modelos;
// Generated 29/11/2017 08:00:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Salida generated by hbm2java
 */
public class Salida  implements java.io.Serializable {


     private Integer idSalida;
     private Material material;
     private Pedido pedido;
     private Usuario usuario;
     private Date fecha;
     private double cantidad;

    public Salida() {
    }

    public Salida(Material material, Pedido pedido, Usuario usuario, Date fecha, double cantidad) {
       this.material = material;
       this.pedido = pedido;
       this.usuario = usuario;
       this.fecha = fecha;
       this.cantidad = cantidad;
    }
   
    public Integer getIdSalida() {
        return this.idSalida;
    }
    
    public void setIdSalida(Integer idSalida) {
        this.idSalida = idSalida;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }




}


