package Modelos;
// Generated 29/11/2017 08:00:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoProducto generated by hbm2java
 */
public class TipoProducto  implements java.io.Serializable {


     private Integer idTipoProducto;
     private String nombre;
     private String estado;
     private Set<TipoProductoYMaterial> tipoProductoYMaterials = new HashSet<TipoProductoYMaterial>(0);
     private Set<Producto> productos = new HashSet<Producto>(0);

    public TipoProducto() {
    }

	
    public TipoProducto(String nombre, String estado) {
        this.nombre = nombre;
        this.estado = estado;
    }
    public TipoProducto(String nombre, String estado, Set<TipoProductoYMaterial> tipoProductoYMaterials, Set<Producto> productos) {
       this.nombre = nombre;
       this.estado = estado;
       this.tipoProductoYMaterials = tipoProductoYMaterials;
       this.productos = productos;
    }
   
    public Integer getIdTipoProducto() {
        return this.idTipoProducto;
    }
    
    public void setIdTipoProducto(Integer idTipoProducto) {
        this.idTipoProducto = idTipoProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<TipoProductoYMaterial> getTipoProductoYMaterials() {
        return this.tipoProductoYMaterials;
    }
    
    public void setTipoProductoYMaterials(Set<TipoProductoYMaterial> tipoProductoYMaterials) {
        this.tipoProductoYMaterials = tipoProductoYMaterials;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


